=== anubees/roadkill/src/Roadkill.Web/Plugins/EmoticonsPlugin/EmoticonsMappings.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="EmoticonsMappings"
            xmlns:xs='http://www.w3.org/2001/XMLSchema'
  >
  <xs:element name="EmoticonsMappings">
      <xs:complexType>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element name="Mapping">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="xs:string" name="Image"/>
                <xs:element type="xs:string" name="Notation"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:choice>
      </xs:complexType>
    </xs:element>
</xs:schema>

=== anubees/roadkill/src/Roadkill.Web/Plugins/EmoticonsPlugin/EmoticonsMappings.xml
<?xml version="1.0" encoding="utf-8" ?>
<EmoticonsMappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation='EmoticonsMappings.xsd'>
  <Mapping>
    <Image>~/Assets/Images/emoticons/smile.png</Image>
    <Notation>{:)}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/sad.png</Image>
    <Notation>{:(}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/tongue.png</Image>
    <Notation>{:P}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/biggrin.png</Image>
    <Notation>{:D}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/wink.png</Image>
    <Notation>{;)}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/thumbs_up.png</Image>
    <Notation>{(y)}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/thumbs_down.png</Image>
    <Notation>{(n)}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/information.png</Image>
    <Notation>{(i)}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/check.png</Image>
    <Notation>{(/)}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/error.png</Image>
    <Notation>{(x)}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/warning.png</Image>
    <Notation>{(!)}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/add.png</Image>
    <Notation>{(+)}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/forbidden.png</Image>
    <Notation>{(-)}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/help_16.png</Image>
    <Notation>{(?)}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/lightbulb_on.png</Image>
    <Notation>{(on)}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/lightbulb.png</Image>
    <Notation>{(off)}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/star_yellow.png</Image>
    <Notation>{(*)}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/star_red.png</Image>
    <Notation>{(*r)}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/star_green.png</Image>
    <Notation>{(*g)}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/star_blue.png</Image>
    <Notation>{(*b)}</Notation>
  </Mapping>
  <Mapping>
    <Image>~/Assets/Images/emoticons/star_yellow.png</Image>
    <Notation>{(*y)}</Notation>
  </Mapping>
</EmoticonsMappings>
